### ISSUE TITLE
Dyntastic import error

### ISSUE THREAD

**Issue by kvanopdorp** [nayaverdier/dyntastic#14]
I just installed version 0.13.0 with pydantic v2 support. When importing the Dyntastic class, I get the below error:

I believe it's a matter of importing FieldInfo vs setting FieldInfo to pydantic.fields.Fiedlnfo. I opened a pull request with slight mods. Feel free to pull or mod as makes more sense to you. 

>>> from dyntastic import Dyntastic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kirk/python-test/.venv/lib/python3.9/site-packages/dyntastic/__init__.py", line 1, in <module>
    from .attr import A, Attr
  File "/Users/kirk/python-test/.venv/lib/python3.9/site-packages/dyntastic/attr.py", line 10, in <module>
    from . import pydantic_compat
  File "/Users/kirk/python-test/.venv/lib/python3.9/site-packages/dyntastic/pydantic_compat.py", line 90, in <module>
    FieldInfo = pydantic.fields.FieldInfo
  File "/Users/kirk/python-test/.venv/lib/python3.9/site-packages/pydantic/__init__.py", line 363, in __getattr__
    return _getattr_migration(attr_name)
  File "/Users/kirk/python-test/.venv/lib/python3.9/site-packages/pydantic/_migration.py", line 306, in wrapper
    raise AttributeError(f'module {module!r} has no attribute {name!r}')
AttributeError: module 'pydantic' has no attribute 'fields'

**Comment by nayaverdier** [comment]
Good catch, looks like this was introduced in pydantic 2.5.0. Thanks for the PR, will deploy shortly.
